CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TYPE "user_role" AS ENUM (
  'CUSTOMER',
  'OWNER',
  'EMPLOYEE',
  'DELIVERY_MAN',
  'ADMIN'
);

CREATE TYPE "account_provider" AS ENUM (
  'GOOGLE',
  'APPLE',
  'META',
  'CARDAPIOGO'
);

CREATE TYPE "cousine_type" AS ENUM (
  'ITALIAN',
  'JAPANESE',
  'MEXICAN',
  'ARABIC',
  'BRAZILIAN',
  'THAI',
  'AMERICAN'
);

CREATE TYPE "shop_type" AS ENUM (
  'RESTAURANT',
  'PHARMACY',
  'TOBBACO',
  'MARKET',
  'CONVENIENCE',
  'PUB'
);

CREATE TYPE "payment_form" AS ENUM (
  'CREDIT_CARD',
  'DEBIT_CARD',
  'PIX',
  'CASH'
);

CREATE TYPE "order_status" AS ENUM (
  'CREATED',
  'ACCEPTED',
  'IN_PROGRESS',
  'FINISHED',
  'CANCELED'
);

CREATE TYPE "weekday" AS ENUM (
  'MONDAY',
  'TUESDAY',
  'WEDNESDAY',
  'THURSDAY',
  'FRIDAY',
  'SATURDAY',
  'SUNDAY'
);

CREATE TABLE "users" (
  "id" UUID UNIQUE PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "profile_id" integer,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar,
  "role" user_role NOT NULL,
  "account_provider" account_provider NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(25) NOT NULL,
  "last_name" varchar(75) NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "phone" varchar(14) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "street" varchar NOT NULL,
  "number" varchar NOT NULL,
  "complement" varchar,
  "district" varchar NOT NULL,
  "zip_code" varchar NOT NULL,
  "city" varchar NOT NULL,
  "state" varchar NOT NULL,
  "latitude" varchar,
  "longitude" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "external_id" UUID UNIQUE DEFAULT (uuid_generate_v4()),
  "name" varchar NOT NULL,
  "active" boolean NOT NULL,
  "cpf_cnpj" varchar UNIQUE NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
  "score" integer NOT NULL,
  "address_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "store_restaurant_type" (
  "id" integer,
  "restaurant_type" cousine_type
);

CREATE TABLE "store_type" (
  "id" integer,
  "type" shop_type
);

CREATE TABLE "store_payment_method" (
  "id" integer,
  "payment_form" payment_form
);

CREATE TABLE "employee" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "store_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "owner" (
  "profile_id" integer,
  "store_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "shipping_value" integer,
  "amount" integer,
  "status" order_status,
  "details" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "order_item" (
  "order_id" integer,
  "item_id" integer
);

CREATE TABLE "item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "restaurant_id" integer,
  "name" varchar,
  "description" varchar,
  "img" varchar,
  "amount" integer,
  "score" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "businessHours" (
  "store_id" integer,
  "weekday" weekday UNIQUE,
  "opening_time" varchar(5),
  "closing_time" varchar(5)
);

ALTER TABLE "users" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "address" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "store" ADD FOREIGN KEY ("address_id") REFERENCES "address" ("id");

ALTER TABLE "store_restaurant_type" ADD FOREIGN KEY ("id") REFERENCES "store" ("id");

ALTER TABLE "store_type" ADD FOREIGN KEY ("id") REFERENCES "store" ("id");

ALTER TABLE "store_payment_method" ADD FOREIGN KEY ("id") REFERENCES "store" ("id");

ALTER TABLE "employee" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "employee" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "owner" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "owner" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");

ALTER TABLE "order" ADD FOREIGN KEY ("profile_id") REFERENCES "profile" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("order_id") REFERENCES "order" ("id");

ALTER TABLE "order_item" ADD FOREIGN KEY ("item_id") REFERENCES "item" ("id");

ALTER TABLE "item" ADD FOREIGN KEY ("restaurant_id") REFERENCES "store" ("id");

ALTER TABLE "businessHours" ADD FOREIGN KEY ("store_id") REFERENCES "store" ("id");
