// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateStore(ctx context.Context, arg CreateStoreParams) error
	IsOwner(ctx context.Context, arg IsOwnerParams) (bool, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) error
}

var _ Querier = (*Queries)(nil)
