// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :exec
INSERT INTO store (id, cpf_cnpj, owner_id, name, active, phone, score, type, address_line_1, address_line_2, neighborhood, city, state, postal_code,
  latitude, longitude, country, created_at, updated_at)
VALUES($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, NOW(), NOW())
`

type CreateStoreParams struct {
	ID           pgtype.UUID `db:"id" json:"id"`
	CpfCnpj      string      `db:"cpf_cnpj" json:"cpf_cnpj"`
	OwnerID      pgtype.UUID `db:"owner_id" json:"owner_id"`
	Name         string      `db:"name" json:"name"`
	Active       bool        `db:"active" json:"active"`
	Phone        string      `db:"phone" json:"phone"`
	Score        int32       `db:"score" json:"score"`
	Type         interface{} `db:"type" json:"type"`
	AddressLine1 string      `db:"address_line_1" json:"address_line_1"`
	AddressLine2 string      `db:"address_line_2" json:"address_line_2"`
	Neighborhood string      `db:"neighborhood" json:"neighborhood"`
	City         string      `db:"city" json:"city"`
	State        string      `db:"state" json:"state"`
	PostalCode   string      `db:"postal_code" json:"postal_code"`
	Latitude     pgtype.Text `db:"latitude" json:"latitude"`
	Longitude    pgtype.Text `db:"longitude" json:"longitude"`
	Country      string      `db:"country" json:"country"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) error {
	_, err := q.db.Exec(ctx, createStore,
		arg.ID,
		arg.CpfCnpj,
		arg.OwnerID,
		arg.Name,
		arg.Active,
		arg.Phone,
		arg.Score,
		arg.Type,
		arg.AddressLine1,
		arg.AddressLine2,
		arg.Neighborhood,
		arg.City,
		arg.State,
		arg.PostalCode,
		arg.Latitude,
		arg.Longitude,
		arg.Country,
	)
	return err
}
