CREATE SCHEMA IF NOT EXISTS cardapio;

CREATE TYPE cardapio."user_role" AS ENUM (
  'Consumer',
  'Owner',
  'Employee',
  'DeliveryMan',
  'Admin'
);

CREATE TYPE cardapio."account_provider" AS ENUM (
  'Google',
  'Apple',
  'Meta'
);

CREATE TYPE cardapio."cousine_types" AS ENUM (
  'ITALIANA',
  'FRANCESA',
  'JAPONESA',
  'PORTUGUESA',
  'MEXICANA',
  'ARABE',
  'BRASILEIRA',
  'TAILANDESA',
  'DOCES',
  'SALGADOS'
);

CREATE TYPE cardapio."order_status" AS ENUM (
  'CREATED',
  'PROGRESS',
  'FINISHED',
  'CANCELED'
);

CREATE TYPE cardapio."weekday" AS ENUM (
  'MONDAY',
  'TUESDAY',
  'WEDNESDAY',
  'THURSDAY',
  'FRIDAY',
  'SATURDAY',
  'SUNDAY'
);

CREATE TABLE cardapio."users" (
  "id" UUID UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar(50),
  "role" cardapio.user_role,
  "account_provider" cardapio.account_provider NOT NULL,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(25) NOT NULL,
  "last_name" varchar(75) NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "phone" varchar(14) NOT NULL,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "street" varchar NOT NULL,
  "number" varchar NOT NULL,
  "complement" varchar NOT NULL,
  "district" varchar NOT NULL,
  "cep" varchar NOT NULL,
  "city" varchar NOT NULL,
  "state" varchar NOT NULL,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."owner" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "users_id" UUID,
  "restaurant_id" integer,
  "created_at" TIMESTAMPTZ,
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."employee" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "users_id" UUID,
  "created_at" TIMESTAMPTZ,
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."employee_restaurant" (
  "employee_id" integer,
  "restaurant_id" integer
);

CREATE TABLE cardapio."restaurant" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "cnpj" varchar UNIQUE NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
  "score" decimal(4,2),
  "address_id" integer NOT NULL,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."restaurant_cousine_type" (
  "restaurant_id" integer NOT NULL,
  "cousine_type_id" integer NOT NULL
);

CREATE TABLE cardapio."cousine_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" cardapio.cousine_types NOT NULL
);

CREATE TABLE cardapio."order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer NOT NULL,
  "shipping_value" decimal(4,2) NOT NULL,
  "total_value" decimal(4,2) NOT NULL,
  "status" cardapio.order_status NOT NULL,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."order_item" (
  "order_id" integer NOT NULL,
  "item_id" integer NOT NULL
);

CREATE TABLE cardapio."item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "restaurant_id" integer NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "img" varchar NOT NULL,
  "value" decimal(4,2) NOT NULL,
  "score" decimal(3,2) NOT NULL,
  "created_at" TIMESTAMPTZ,
  "updated_at" TIMESTAMPTZ,
  "deleted_at" TIMESTAMPTZ
);

CREATE TABLE cardapio."payment_method" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "description" varchar NOT NULL,
  "isOnline" boolean NOT NULL
);

CREATE TABLE cardapio."businessHour" (
  "restaurant_id" integer NOT NULL,
  "weekday" cardapio.weekday NOT NULL,
  "opening_time" TIME NOT NULL,
  "closing_time" TIME NOT NULL
);

CREATE TABLE cardapio."restaurant_payment_method" (
  "payment_method_id" integer NOT NULL,
  "restaurant_id" integer NOT NULL
);

CREATE TABLE cardapio."profile_restaurant" (
  "profile_id" integer NOT NULL,
  "restaurant_id" integer NOT NULL
);

ALTER TABLE cardapio."users" ADD FOREIGN KEY ("profile_id") REFERENCES cardapio."profile" ("id");

ALTER TABLE cardapio."address" ADD FOREIGN KEY ("profile_id") REFERENCES cardapio."profile" ("id");

ALTER TABLE cardapio."owner" ADD FOREIGN KEY ("users_id") REFERENCES cardapio."users" ("id");

ALTER TABLE cardapio."owner" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");

ALTER TABLE cardapio."employee" ADD FOREIGN KEY ("users_id") REFERENCES cardapio."users" ("id");

ALTER TABLE cardapio."employee_restaurant" ADD FOREIGN KEY ("employee_id") REFERENCES cardapio."employee" ("id");

ALTER TABLE cardapio."employee_restaurant" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");

ALTER TABLE cardapio."restaurant" ADD FOREIGN KEY ("address_id") REFERENCES cardapio."address" ("id");

ALTER TABLE cardapio."restaurant_cousine_type" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");

ALTER TABLE cardapio."restaurant_cousine_type" ADD FOREIGN KEY ("cousine_type_id") REFERENCES cardapio."cousine_type" ("id");

ALTER TABLE cardapio."order" ADD FOREIGN KEY ("profile_id") REFERENCES cardapio."profile" ("id");

ALTER TABLE cardapio."order_item" ADD FOREIGN KEY ("order_id") REFERENCES cardapio."order" ("id");

ALTER TABLE cardapio."order_item" ADD FOREIGN KEY ("item_id") REFERENCES cardapio."item" ("id");

ALTER TABLE cardapio."item" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");

ALTER TABLE cardapio."businessHour" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");

ALTER TABLE cardapio."restaurant_payment_method" ADD FOREIGN KEY ("payment_method_id") REFERENCES cardapio."payment_method" ("id");

ALTER TABLE cardapio."restaurant_payment_method" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");

ALTER TABLE cardapio."profile_restaurant" ADD FOREIGN KEY ("profile_id") REFERENCES cardapio."profile" ("id");

ALTER TABLE cardapio."profile_restaurant" ADD FOREIGN KEY ("restaurant_id") REFERENCES cardapio."restaurant" ("id");