// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	GetProfile(ctx context.Context, id int32) (CardapioProfile, error)
	GetUser(ctx context.Context, id uuid.UUID) (CardapioUser, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UpdateProfileCpf(ctx context.Context, arg UpdateProfileCpfParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) error
}

var _ Querier = (*Queries)(nil)
