@baseUrl = http://localhost:8080/api/v1

# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "trevor.philips@example.com",
    "password": "teste123"
}

###

@authToken = {{login.response.headers.Set-Cookie}}

# @name listUsers
GET {{baseUrl}}/user
    ?items=10
    &page=1
Content-Type: application/json
Cookie: {{authToken}}
###

# @name getUser
GET {{baseUrl}}/user/34e1b6a6-c241-4006-be1d-6255393edb7c
Content-Type: application/json
Cookie: {{authToken}}
###

# @name updateUser
PUT {{baseUrl}}/user
Content-Type: application/json
Cookie: {{authToken}}

{
  "id": "34e1b6a6-c241-4006-be1d-6255393edb7c",
  "email": "trevor.philips@example.com",
  "password": "teste123",
  "role": "DeliveryMan"
}
###



