version: "2"
sql:
  - engine: "postgresql"
    queries: "../internal/infrastructure/database/sql/query.sql"
    schema: "../internal/infrastructure/database/sql/schema.sql"
    gen:
      go:
        package: "sqlc"
        out: "../internal/infrastructure/database/sqlc"
        sql_package: "pgx/v5"
        emit_db_tags: true
        emit_prepared_queries: true
        emit_interface: true
        emit_json_tags: true
        emit_exact_table_names: true
        json_tags_case_style: "snake"