# Nginx
# @baseUrl = http://localhost/api

# Local
@baseUrl = http://localhost:8080/api

# @name login
POST {{baseUrl}}/v1/login
Content-Type: application/json

{
    "email": "trevor.philips@example.com",
    "password": "teste123"
}
###

@authToken = {{login.response.headers.Set-Cookie}}

# @name createUser
POST {{baseUrl}}/v1/user
Content-Type: application/json

{
  "email": "apollo.creed@example.com",
  "password": "teste123",
  "role": "Owner",
  "account_provider": "Google"
}
###

# @name listUsers
GET {{baseUrl}}/v1/user
    ?items=10
    &page=1
Content-Type: application/json
Cookie: {{authToken}}
###

# @name getUser
GET {{baseUrl}}/v1/user/a0803f64-82c3-4f8f-9c12-bc8fcb54440b
Content-Type: application/json
Cookie: {{authToken}}
###

# @name updateUser
PUT {{baseUrl}}/v1/user
Content-Type: application/json
Cookie: {{authToken}}
{
  "id": "34e1b6a6-c241-4006-be1d-6255393edb7c",
  "email": "trevor.philips@example.com",
  "password": "teste123",
  "role": "DeliveryMan"
}
###


# @name healthcheck
GET {{baseUrl}}/v1/health
Content-Type: application/json
###


