basePath: /api
consumes:
- application/json
definitions:
  authentication.SignInParams:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  entity.JWT:
    properties:
      access_token:
        type: string
      expires_in:
        type: integer
      id_token:
        type: string
      not-before-policy:
        type: integer
      refresh_expires_in:
        type: integer
      refresh_token:
        type: string
      scope:
        type: string
      session_state:
        type: string
      token_type:
        type: string
    type: object
  user.CreateParams:
    properties:
      email:
        type: string
      password:
        type: string
      profile:
        $ref: '#/definitions/user.CreateProfileParams'
    required:
    - email
    - password
    type: object
  user.CreateProfileParams:
    properties:
      document:
        type: string
      lastName:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - document
    - lastName
    - name
    - phone
    type: object
  user.UpdateProfileParams:
    properties:
      lastName:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - lastName
    - name
    - phone
    type: object
  xerrors.ErrorResponse:
    properties:
      details: {}
      error:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: gustavo081900@gmail.com
    name: Gustavo Ferreira de Jesus
  description: Documentação da API de delivery Cardapiogo.
  title: Cardapiogo API
  version: "1.0"
paths:
  /v1/auth/sign-in:
    post:
      consumes:
      - application/json
      description: Authenticate a user using email and password and issue a JWT on
        successful login.
      parameters:
      - description: SignInParams
        in: body
        name: request
        schema:
          $ref: '#/definitions/authentication.SignInParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
      summary: Sign-In with email and password
      tags:
      - Authentication
  /v1/auth/sign-up:
    post:
      consumes:
      - application/json
      description: Sign-Up with local credentials and data
      parameters:
      - description: CreateUserParams
        in: body
        name: request
        schema:
          $ref: '#/definitions/user.CreateParams'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
      summary: Sign-Up with local credentials and data
      tags:
      - Authentication
  /v1/auth/test/authentication:
    get:
      consumes:
      - application/json
      description: Route for test authentication middleware
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
      security:
      - Bearer Token: []
      summary: Route for test authentication middleware
      tags:
      - Authentication
  /v1/auth/test/authorization:
    get:
      consumes:
      - application/json
      description: Route for test authorization middleware
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.JWT'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
      security:
      - Bearer Token: []
      summary: Route for test authorization middleware
      tags:
      - Authentication
  /v1/user:
    put:
      consumes:
      - application/json
      description: Update user profile
      parameters:
      - description: UpdateProfileParams
        in: body
        name: request
        schema:
          $ref: '#/definitions/user.UpdateProfileParams'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
        "502":
          description: Bad Gateway
          schema:
            $ref: '#/definitions/xerrors.ErrorResponse'
      summary: Update user profile
      tags:
      - User
produces:
- application/json
securityDefinitions:
  Bearer Token:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
