CREATE TABLE "cardapiogo"."users" (
  "id" UUID UNIQUE PRIMARY KEY DEFAULT (uuid_generate_v4()),
  "profile_id" integer,
  "email" varchar UNIQUE NOT NULL,
  "password" varchar,
  "role" "cardapiogo".user_role,
  "account_provider" "cardapiogo".account_provider NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."profile" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar(25) NOT NULL,
  "last_name" varchar(75) NOT NULL,
  "cpf" varchar(11) UNIQUE NOT NULL,
  "phone" varchar(14) NOT NULL,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."address" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "street" varchar NOT NULL,
  "number" varchar NOT NULL,
  "complement" varchar,
  "district" varchar NOT NULL,
  "zip_code" varchar NOT NULL,
  "city" varchar NOT NULL,
  "state" varchar NOT NULL,
  "latitude" varchar,
  "longitude" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."store" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "name" varchar NOT NULL,
  "active" boolean NOT NULL,
  "cpf_cnpj" varchar UNIQUE NOT NULL,
  "phone" varchar UNIQUE NOT NULL,
  "score" integer NOT NULL,
  "address_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."store_restaurant_type" (
  "id" integer,
  "restaurant_type" "cardapiogo".cousine_type
);

CREATE TABLE "cardapiogo"."store_type" (
  "id" integer,
  "type" "cardapiogo".shop_type
);

CREATE TABLE "cardapiogo"."store_payment_method" (
  "id" integer,
  "payment_form" "cardapiogo".payment_form
);

CREATE TABLE "cardapiogo"."employee" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "store_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."owner" (
  "profile_id" integer,
  "store_id" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."order" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "profile_id" integer,
  "shipping_value" integer,
  "amount" integer,
  "status" "cardapiogo".order_status,
  "details" varchar,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."order_item" (
  "order_id" integer,
  "item_id" integer
);

CREATE TABLE "cardapiogo"."item" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "restaurant_id" integer,
  "name" varchar,
  "description" varchar,
  "img" varchar,
  "amount" integer,
  "score" integer,
  "created_at" timestamp,
  "updated_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "cardapiogo"."businessHours" (
  "store_id" integer,
  "weekday" "cardapiogo".weekday UNIQUE,
  "opening_time" varchar(5),
  "closing_time" varchar(5)
);

ALTER TABLE "cardapiogo"."users" ADD FOREIGN KEY ("profile_id") REFERENCES "cardapiogo"."profile" ("id");

ALTER TABLE "cardapiogo"."address" ADD FOREIGN KEY ("profile_id") REFERENCES "cardapiogo"."profile" ("id");

ALTER TABLE "cardapiogo"."store" ADD FOREIGN KEY ("address_id") REFERENCES "cardapiogo"."address" ("id");

ALTER TABLE "cardapiogo"."store_restaurant_type" ADD FOREIGN KEY ("id") REFERENCES "cardapiogo"."store" ("id");

ALTER TABLE "cardapiogo"."store_type" ADD FOREIGN KEY ("id") REFERENCES "cardapiogo"."store" ("id");

ALTER TABLE "cardapiogo"."store_payment_method" ADD FOREIGN KEY ("id") REFERENCES "cardapiogo"."store" ("id");

ALTER TABLE "cardapiogo"."employee" ADD FOREIGN KEY ("profile_id") REFERENCES "cardapiogo"."profile" ("id");

ALTER TABLE "cardapiogo"."employee" ADD FOREIGN KEY ("store_id") REFERENCES "cardapiogo"."store" ("id");

ALTER TABLE "cardapiogo"."owner" ADD FOREIGN KEY ("profile_id") REFERENCES "cardapiogo"."profile" ("id");

ALTER TABLE "cardapiogo"."owner" ADD FOREIGN KEY ("store_id") REFERENCES "cardapiogo"."store" ("id");

ALTER TABLE "cardapiogo"."order" ADD FOREIGN KEY ("profile_id") REFERENCES "cardapiogo"."profile" ("id");

ALTER TABLE "cardapiogo"."order_item" ADD FOREIGN KEY ("order_id") REFERENCES "cardapiogo"."order" ("id");

ALTER TABLE "cardapiogo"."order_item" ADD FOREIGN KEY ("item_id") REFERENCES "cardapiogo"."item" ("id");

ALTER TABLE "cardapiogo"."item" ADD FOREIGN KEY ("restaurant_id") REFERENCES "cardapiogo"."store" ("id");

ALTER TABLE "cardapiogo"."businessHours" ADD FOREIGN KEY ("store_id") REFERENCES "cardapiogo"."store" ("id");
