name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22.5'
      
      - name: Create .env file
        run: |
          APP_REPO=${{ vars.APP_REPO }} >> .env
          APP_NAME=${{ vars.APP_NAME }} >> .env
          echo .env

      - name: Run Tests
        run: make lint

      - name: Run Unit Tests
        run: make test-unit

      - name: Run Integration Tests
        run: make test-integration

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push API
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          push: true
          tags: |
            ${{ vars.APP_REPO }}/${{ vars.APP_NAME }}:${{ github.sha }}
            ${{ vars.APP_REPO }}/${{ vars.APP_NAME }}:latest